#spring:
#  config:
#    import: optional:configserver:http://localhost:8000
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
#    discovery:
#      locator:
#        enabled: true
#    routes:
#      - id: MICROSERVICE-A
#        uri: lb://MICROSERVICE-A
#        predicates:
#          - Path=/microservice-a/**
#      - id: MICROSERVICE-B
#        uri: lb://MICROSERVICE-B
#        predicates:
#          - Path=/microservice-b/**
#
#
##
##    cloud:
##      gateway:
##        routes:
##          - id: MICROSERVICE-A
##            uri: lb://MICROSERVICE-A
##            predicates:
##              - Path=/microservice/a/**
##
##          - id: MICROSERVICE-B
##            uri: lb://MICROSERVICE-B
##            predicates:
##              - Path=/microservice/b/**
#
##
##logging:
##  level:
##    org:
##      springframework:
##        cloud:
##          gateway: DEBUG
#
##logging:
##  level:
##    org.springframework.cloud.gateway: TRACE
##    org.springframework.http.server.reactive: DEBUG
##    org.springframework.web.reactive: DEBUG
##    reactor.ipc.netty: DEBUG
#server:
#  port: 9000
##    reactor.netty: DEBUG
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

server:
  port: 8085

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: MICROSERVICE-A
          uri: lb://MICROSERVICE-A
          predicates:
            - Path=/microservice-a/**

        - id: MICROSERVICE-B
          uri: lb://MICROSERVICE-B
          predicates:
            - Path=/microservice-b/**

        - id: AUTHENTICATION-SERVER
          uri: lb://AUTHENTICATION-SERVER
          predicates:
            - Path=/secure/**




eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#okta configuration for api gateway

#okta:
#  oauth2:
#    issuer: https://dev-77584981.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa7w65a24Px9Oyms5d7
#    client-secret: JfsTTqODW21uapbbhKjW42sGzjcNs86GN7WL5dfU
#    scopes: openid, profile, email, offline_access