version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - C:\Users\sriva\Desktop\microservices-spring-cloud\Microservices-communication\data\redis:/var/lib/rabbitmq


  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - C:\Users\sriva\Desktop\microservices-spring-cloud\Microservices-communication\data\kafka:/var/lib/rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - C:\Users\sriva\Desktop\microservices-spring-cloud\Microservices-communication\data\rabbitmq:/var/lib/rabbitmq


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user-details
    ports:
      - "5435:5432"
    networks:
      - pg-network
    volumes:
      - C:\Users\sriva\Desktop\microservices-spring-cloud\Microservices-communication\data\postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pg-network

volumes:
  redis-data:
    driver: local
  kafka-data:
    driver: local
  rabbitmq-data:
    driver: local
  postgres-data:
    driver: local

networks:
  pg-network:
    driver: bridge